#!/usr/bin/env bash
set -e

cat >/app/.env.development.local <<EOL
REACT_APP_SERVER_HOSTNAME=${REACT_APP_SERVER_HOSTNAME}
REACT_APP_SERVER_PORT=${REACT_APP_SERVER_PORT}

REACT_APP_API_HOSTNAME=${REACT_APP_API_HOSTNAME}
REACT_APP_API_PORT=${REACT_APP_API_PORT}

REACT_APP_WORKER_MANAGER_HOSTNAME=${REACT_APP_WORKER_MANAGER_HOSTNAME}
REACT_APP_WORKER_MANAGER_PORT=${REACT_APP_WORKER_MANAGER_PORT}

REACT_APP_S3_HOSTNAME=${REACT_APP_S3_HOSTNAME}
REACT_APP_S3_PORT=${REACT_APP_S3_PORT}
REACT_APP_S3_BUCKET_NAME=${REACT_APP_S3_BUCKET_NAME}
EOL